clc;
clear;
close all;
slices = categorical({'eMBB','URLLC','mMTC','Private','IoT'});
utilization = [85 70 60 75 50];
figure;
bar(slices, utilization);
grid on;
xlabel('Network Slice Type');
ylabel('Slice Utilization (%)');
title('Slice Utilization in 5G Network Slicing');
ylim([0 100]);